export const ACTION_GET_Detail_DATA = 'ACTION_GET_DATA';

export const ACTION_USER_SAVE = 'ACTION_USER_SAVE';

export const ACTION_USER_MODIFY = 'ACTION_USER_MODIFY';

export const ACTION_USER_CLEAR = 'ACTION_USER_CLEAR';

export const ACTION_FETCH_DATA = 'ACTION_FETCH_DATA'